# coding: utf-8

"""
    CatalogService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_image_create_dto import ItemImageCreateDto

class TestItemImageCreateDto(unittest.TestCase):
    """ItemImageCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemImageCreateDto:
        """Test ItemImageCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemImageCreateDto`
        """
        model = ItemImageCreateDto()
        if include_optional:
            return ItemImageCreateDto(
                id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                business_id = '01234567891011121314151617181920212223242526272829303132333435',
                business_profile_record_id = '01234567891011121314151617181920212223242526272829303132333435',
                item_id = '01234567891011121314151617181920212223242526272829303132333435',
                is_item_mozaic_bg = True,
                m_d5_hash = '012345678910111213141516171819202122232425262728293031',
                metadata = '',
                file_upload_url = '',
                file_name = '',
                title = '',
                abstract = '',
                author = '',
                key_words = '',
                notes = '',
                content_type = '',
                file_length = 0,
                valid_response = True,
                social_profile_id = '01234567891011121314151617181920212223242526272829303132333435',
                parent_file_upload_id = '01234567891011121314151617181920212223242526272829303132333435',
                account_holder_id = '01234567891011121314151617181920212223242526272829303132333435'
            )
        else:
            return ItemImageCreateDto(
                business_id = '01234567891011121314151617181920212223242526272829303132333435',
                file_name = '',
        )
        """

    def testItemImageCreateDto(self):
        """Test ItemImageCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
