# coding: utf-8

"""
    CatalogService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_question_dto_list_envelope import ItemQuestionDtoListEnvelope

class TestItemQuestionDtoListEnvelope(unittest.TestCase):
    """ItemQuestionDtoListEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemQuestionDtoListEnvelope:
        """Test ItemQuestionDtoListEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemQuestionDtoListEnvelope`
        """
        model = ItemQuestionDtoListEnvelope()
        if include_optional:
            return ItemQuestionDtoListEnvelope(
                is_success = True,
                error_message = '',
                correlation_id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                activity_id = '',
                result = [
                    openapi_client.models.item_question_dto.ItemQuestionDto(
                        id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        title = '', 
                        needs_revision = True, 
                        question = '', 
                        social_profile_id = '', 
                        business_id = '', 
                        item_id = '', )
                    ]
            )
        else:
            return ItemQuestionDtoListEnvelope(
        )
        """

    def testItemQuestionDtoListEnvelope(self):
        """Test ItemQuestionDtoListEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
