# coding: utf-8

"""
    AccountingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.fiscal_regimes_api import FiscalRegimesApi


class TestFiscalRegimesApi(unittest.TestCase):
    """FiscalRegimesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FiscalRegimesApi()

    def tearDown(self) -> None:
        pass

    def test_create_fiscal_regime(self) -> None:
        """Test case for create_fiscal_regime

        Create a fiscal regime
        """
        pass

    def test_delete_fiscal_regime(self) -> None:
        """Test case for delete_fiscal_regime

        Delete a fiscal regime
        """
        pass

    def test_get_fiscal_regime(self) -> None:
        """Test case for get_fiscal_regime

        Get fiscal regime by ID
        """
        pass

    def test_get_fiscal_regimes(self) -> None:
        """Test case for get_fiscal_regimes

        Get fiscal regimes for an authority
        """
        pass

    def test_get_fiscal_regimes_count(self) -> None:
        """Test case for get_fiscal_regimes_count

        Get fiscal regimes count
        """
        pass

    def test_update_fiscal_regime(self) -> None:
        """Test case for update_fiscal_regime

        Update a fiscal regime
        """
        pass


if __name__ == '__main__':
    unittest.main()
