# coding: utf-8

"""
    AccountingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.2.5401
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.expense_claims_api import ExpenseClaimsApi


class TestExpenseClaimsApi(unittest.TestCase):
    """ExpenseClaimsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpenseClaimsApi()

    def tearDown(self) -> None:
        pass

    def test_create_expense_claim(self) -> None:
        """Test case for create_expense_claim

        Create an expense claim
        """
        pass

    def test_delete_expense_claim(self) -> None:
        """Test case for delete_expense_claim

        Delete an expense claim
        """
        pass

    def test_get_expense_claim(self) -> None:
        """Test case for get_expense_claim

        Get an expense claim by id
        """
        pass

    def test_get_expense_claims(self) -> None:
        """Test case for get_expense_claims

        Get all expense claims for a tenant
        """
        pass

    def test_get_expense_claims_count(self) -> None:
        """Test case for get_expense_claims_count

        Get the count of expense claims for a tenant
        """
        pass

    def test_update_expense_claim(self) -> None:
        """Test case for update_expense_claim

        Update an expense claim
        """
        pass


if __name__ == '__main__':
    unittest.main()
