# coding: utf-8

"""
    PricingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.currency_id import CurrencyId
from openapi_client.models.money import Money
from typing import Optional, Set
from typing_extensions import Self

class ItemPriceCalculation(BaseModel):
    """
    ItemPriceCalculation
    """ # noqa: E501
    quantity: Optional[Union[StrictFloat, StrictInt]] = None
    item_id: Optional[StrictStr] = Field(default=None, alias="itemId")
    item: Optional[StrictStr] = None
    unit_id: Optional[StrictStr] = Field(default=None, alias="unitId")
    unit_group_id: Optional[StrictStr] = Field(default=None, alias="unitGroupId")
    price_id: Optional[StrictStr] = Field(default=None, alias="priceId")
    price_list_id: Optional[StrictStr] = Field(default=None, alias="priceListId")
    discount_id: Optional[StrictStr] = Field(default=None, alias="discountId")
    discount_list_id: Optional[StrictStr] = Field(default=None, alias="discountListId")
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    enrollment_id: Optional[StrictStr] = Field(default=None, alias="enrollmentId")
    rounding_policy_id: Optional[StrictStr] = Field(default=None, alias="roundingPolicyId")
    timestamp: Optional[datetime] = None
    effective_discount_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="effectiveDiscountPercent")
    effective_tax_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="effectiveTaxPercent")
    currency_id: Optional[StrictStr] = Field(default=None, alias="currencyId")
    currency: Optional[CurrencyId] = None
    total_base_amount: Optional[Money] = Field(default=None, alias="totalBaseAmount")
    total_profit_amount: Optional[Money] = Field(default=None, alias="totalProfitAmount")
    total_detail_amount: Optional[Money] = Field(default=None, alias="totalDetailAmount")
    total_discounts_amount: Optional[Money] = Field(default=None, alias="totalDiscountsAmount")
    total_surcharges_amount: Optional[Money] = Field(default=None, alias="totalSurchargesAmount")
    total_tax_base_amount: Optional[Money] = Field(default=None, alias="totalTaxBaseAmount")
    total_tax_amount: Optional[Money] = Field(default=None, alias="totalTaxAmount")
    total_w_tax_amount: Optional[Money] = Field(default=None, alias="totalWTaxAmount")
    total_shipping_cost_amount: Optional[Money] = Field(default=None, alias="totalShippingCostAmount")
    total_shipping_tax_amount: Optional[Money] = Field(default=None, alias="totalShippingTaxAmount")
    total_amount: Optional[Money] = Field(default=None, alias="totalAmount")
    __properties: ClassVar[List[str]] = ["quantity", "itemId", "item", "unitId", "unitGroupId", "priceId", "priceListId", "discountId", "discountListId", "tenantId", "enrollmentId", "roundingPolicyId", "timestamp", "effectiveDiscountPercent", "effectiveTaxPercent", "currencyId", "currency", "totalBaseAmount", "totalProfitAmount", "totalDetailAmount", "totalDiscountsAmount", "totalSurchargesAmount", "totalTaxBaseAmount", "totalTaxAmount", "totalWTaxAmount", "totalShippingCostAmount", "totalShippingTaxAmount", "totalAmount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ItemPriceCalculation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "effective_discount_percent",
            "effective_tax_percent",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_base_amount
        if self.total_base_amount:
            _dict['totalBaseAmount'] = self.total_base_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_profit_amount
        if self.total_profit_amount:
            _dict['totalProfitAmount'] = self.total_profit_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_detail_amount
        if self.total_detail_amount:
            _dict['totalDetailAmount'] = self.total_detail_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_discounts_amount
        if self.total_discounts_amount:
            _dict['totalDiscountsAmount'] = self.total_discounts_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_surcharges_amount
        if self.total_surcharges_amount:
            _dict['totalSurchargesAmount'] = self.total_surcharges_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_tax_base_amount
        if self.total_tax_base_amount:
            _dict['totalTaxBaseAmount'] = self.total_tax_base_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_tax_amount
        if self.total_tax_amount:
            _dict['totalTaxAmount'] = self.total_tax_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_w_tax_amount
        if self.total_w_tax_amount:
            _dict['totalWTaxAmount'] = self.total_w_tax_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_shipping_cost_amount
        if self.total_shipping_cost_amount:
            _dict['totalShippingCostAmount'] = self.total_shipping_cost_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_shipping_tax_amount
        if self.total_shipping_tax_amount:
            _dict['totalShippingTaxAmount'] = self.total_shipping_tax_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_amount
        if self.total_amount:
            _dict['totalAmount'] = self.total_amount.to_dict()
        # set to None if item_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_id is None and "item_id" in self.model_fields_set:
            _dict['itemId'] = None

        # set to None if item (nullable) is None
        # and model_fields_set contains the field
        if self.item is None and "item" in self.model_fields_set:
            _dict['item'] = None

        # set to None if unit_id (nullable) is None
        # and model_fields_set contains the field
        if self.unit_id is None and "unit_id" in self.model_fields_set:
            _dict['unitId'] = None

        # set to None if unit_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.unit_group_id is None and "unit_group_id" in self.model_fields_set:
            _dict['unitGroupId'] = None

        # set to None if price_id (nullable) is None
        # and model_fields_set contains the field
        if self.price_id is None and "price_id" in self.model_fields_set:
            _dict['priceId'] = None

        # set to None if price_list_id (nullable) is None
        # and model_fields_set contains the field
        if self.price_list_id is None and "price_list_id" in self.model_fields_set:
            _dict['priceListId'] = None

        # set to None if discount_id (nullable) is None
        # and model_fields_set contains the field
        if self.discount_id is None and "discount_id" in self.model_fields_set:
            _dict['discountId'] = None

        # set to None if discount_list_id (nullable) is None
        # and model_fields_set contains the field
        if self.discount_list_id is None and "discount_list_id" in self.model_fields_set:
            _dict['discountListId'] = None

        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if enrollment_id (nullable) is None
        # and model_fields_set contains the field
        if self.enrollment_id is None and "enrollment_id" in self.model_fields_set:
            _dict['enrollmentId'] = None

        # set to None if rounding_policy_id (nullable) is None
        # and model_fields_set contains the field
        if self.rounding_policy_id is None and "rounding_policy_id" in self.model_fields_set:
            _dict['roundingPolicyId'] = None

        # set to None if currency_id (nullable) is None
        # and model_fields_set contains the field
        if self.currency_id is None and "currency_id" in self.model_fields_set:
            _dict['currencyId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ItemPriceCalculation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quantity": obj.get("quantity"),
            "itemId": obj.get("itemId"),
            "item": obj.get("item"),
            "unitId": obj.get("unitId"),
            "unitGroupId": obj.get("unitGroupId"),
            "priceId": obj.get("priceId"),
            "priceListId": obj.get("priceListId"),
            "discountId": obj.get("discountId"),
            "discountListId": obj.get("discountListId"),
            "tenantId": obj.get("tenantId"),
            "enrollmentId": obj.get("enrollmentId"),
            "roundingPolicyId": obj.get("roundingPolicyId"),
            "timestamp": obj.get("timestamp"),
            "effectiveDiscountPercent": obj.get("effectiveDiscountPercent"),
            "effectiveTaxPercent": obj.get("effectiveTaxPercent"),
            "currencyId": obj.get("currencyId"),
            "currency": CurrencyId.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "totalBaseAmount": Money.from_dict(obj["totalBaseAmount"]) if obj.get("totalBaseAmount") is not None else None,
            "totalProfitAmount": Money.from_dict(obj["totalProfitAmount"]) if obj.get("totalProfitAmount") is not None else None,
            "totalDetailAmount": Money.from_dict(obj["totalDetailAmount"]) if obj.get("totalDetailAmount") is not None else None,
            "totalDiscountsAmount": Money.from_dict(obj["totalDiscountsAmount"]) if obj.get("totalDiscountsAmount") is not None else None,
            "totalSurchargesAmount": Money.from_dict(obj["totalSurchargesAmount"]) if obj.get("totalSurchargesAmount") is not None else None,
            "totalTaxBaseAmount": Money.from_dict(obj["totalTaxBaseAmount"]) if obj.get("totalTaxBaseAmount") is not None else None,
            "totalTaxAmount": Money.from_dict(obj["totalTaxAmount"]) if obj.get("totalTaxAmount") is not None else None,
            "totalWTaxAmount": Money.from_dict(obj["totalWTaxAmount"]) if obj.get("totalWTaxAmount") is not None else None,
            "totalShippingCostAmount": Money.from_dict(obj["totalShippingCostAmount"]) if obj.get("totalShippingCostAmount") is not None else None,
            "totalShippingTaxAmount": Money.from_dict(obj["totalShippingTaxAmount"]) if obj.get("totalShippingTaxAmount") is not None else None,
            "totalAmount": Money.from_dict(obj["totalAmount"]) if obj.get("totalAmount") is not None else None
        })
        return _obj


