# coding: utf-8

"""
    SystemService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.1.4089
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account_holder_create_dto import AccountHolderCreateDto

class TestAccountHolderCreateDto(unittest.TestCase):
    """AccountHolderCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountHolderCreateDto:
        """Test AccountHolderCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountHolderCreateDto`
        """
        model = AccountHolderCreateDto()
        if include_optional:
            return AccountHolderCreateDto(
                id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                qualified_name = '',
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                first_name = '',
                last_name = '',
                public_name = '',
                id_provider = '',
                gender = 0,
                email = '',
                about = '',
                status = '',
                job_title = '',
                git_hub_url = '',
                website_url = '',
                twitter_url = '',
                facebook_url = '',
                you_tube_url = '',
                linked_in_url = '',
                instagram_url = '',
                timezone_id = '',
                language_id = '',
                currency_id = '',
                country_id = '',
                state_id = '',
                city_id = '',
                password = ''
            )
        else:
            return AccountHolderCreateDto(
        )
        """

    def testAccountHolderCreateDto(self):
        """Test AccountHolderCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
