# coding: utf-8

"""
    SystemService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.carts_api import CartsApi


class TestCartsApi(unittest.TestCase):
    """CartsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CartsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_system_cart(self) -> None:
        """Test case for delete_system_cart

        Delete a system cart
        """
        pass

    def test_get_system_cart_by_id(self) -> None:
        """Test case for get_system_cart_by_id

        Retrieve a single system cart by its ID
        """
        pass

    def test_get_system_carts(self) -> None:
        """Test case for get_system_carts

        Retrieve a list of system carts
        """
        pass

    def test_get_system_carts_count(self) -> None:
        """Test case for get_system_carts_count

        Get the count of system carts
        """
        pass


if __name__ == '__main__':
    unittest.main()
