# coding: utf-8

"""
    MarketingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.2.5401
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.marketing_areas_api import MarketingAreasApi


class TestMarketingAreasApi(unittest.TestCase):
    """MarketingAreasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketingAreasApi()

    def tearDown(self) -> None:
        pass

    def test_create_marketing_area_async(self) -> None:
        """Test case for create_marketing_area_async

        Create a marketing area
        """
        pass

    def test_delete_marketing_area_async(self) -> None:
        """Test case for delete_marketing_area_async

        Delete a marketing area
        """
        pass

    def test_get_marketing_area_by_id_async(self) -> None:
        """Test case for get_marketing_area_by_id_async

        Get marketing area by ID
        """
        pass

    def test_get_marketing_areas_async(self) -> None:
        """Test case for get_marketing_areas_async

        Get marketing areas
        """
        pass

    def test_get_marketing_areas_count_async(self) -> None:
        """Test case for get_marketing_areas_count_async

        Count marketing areas
        """
        pass

    def test_update_marketing_area_async(self) -> None:
        """Test case for update_marketing_area_async

        Update a marketing area
        """
        pass


if __name__ == '__main__':
    unittest.main()
