# coding: utf-8

"""
    LearningService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.course_cohorts_api import CourseCohortsApi


class TestCourseCohortsApi(unittest.TestCase):
    """CourseCohortsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CourseCohortsApi()

    def tearDown(self) -> None:
        pass

    def test_create_course_cohort_async(self) -> None:
        """Test case for create_course_cohort_async

        Create a new course cohort
        """
        pass

    def test_delete_course_cohort_async(self) -> None:
        """Test case for delete_course_cohort_async

        Delete a course cohort
        """
        pass

    def test_get_course_cohort_by_id_async(self) -> None:
        """Test case for get_course_cohort_by_id_async

        Get course cohort by ID
        """
        pass

    def test_get_course_cohorts_async(self) -> None:
        """Test case for get_course_cohorts_async

        Get all course cohorts
        """
        pass

    def test_get_course_cohorts_count_async(self) -> None:
        """Test case for get_course_cohorts_count_async

        Get course cohorts count
        """
        pass

    def test_update_course_cohort_async(self) -> None:
        """Test case for update_course_cohort_async

        Update a course cohort
        """
        pass


if __name__ == '__main__':
    unittest.main()
