# coding: utf-8

"""
    ActivitiesService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.2.5532
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activity_type_create_dto import ActivityTypeCreateDto

class TestActivityTypeCreateDto(unittest.TestCase):
    """ActivityTypeCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityTypeCreateDto:
        """Test ActivityTypeCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityTypeCreateDto`
        """
        model = ActivityTypeCreateDto()
        if include_optional:
            return ActivityTypeCreateDto(
                id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = ''
            )
        else:
            return ActivityTypeCreateDto(
        )
        """

    def testActivityTypeCreateDto(self):
        """Test ActivityTypeCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
