# coding: utf-8

"""
    WalletsService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bank_account_update_dto import BankAccountUpdateDto

class TestBankAccountUpdateDto(unittest.TestCase):
    """BankAccountUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankAccountUpdateDto:
        """Test BankAccountUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankAccountUpdateDto`
        """
        model = BankAccountUpdateDto()
        if include_optional:
            return BankAccountUpdateDto(
                name = '',
                iban = '',
                swift = '',
                branch_code = '',
                bank_account_number = '',
                qualified_name = '',
                bank_id = '',
                bank_profile_id = ''
            )
        else:
            return BankAccountUpdateDto(
        )
        """

    def testBankAccountUpdateDto(self):
        """Test BankAccountUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
