# coding: utf-8

"""
    WalletsService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_chargeback_dto import PaymentChargebackDto

class TestPaymentChargebackDto(unittest.TestCase):
    """PaymentChargebackDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentChargebackDto:
        """Test PaymentChargebackDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentChargebackDto`
        """
        model = PaymentChargebackDto()
        if include_optional:
            return PaymentChargebackDto(
                id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                request_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payment_id = '',
                bank_profile_id = '',
                bank_profile_name = '',
                total_fees = 1.337
            )
        else:
            return PaymentChargebackDto(
        )
        """

    def testPaymentChargebackDto(self):
        """Test PaymentChargebackDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
