# coding: utf-8

"""
    LogisticsService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_pick_list_entry_dto_envelope import ItemPickListEntryDtoEnvelope

class TestItemPickListEntryDtoEnvelope(unittest.TestCase):
    """ItemPickListEntryDtoEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemPickListEntryDtoEnvelope:
        """Test ItemPickListEntryDtoEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemPickListEntryDtoEnvelope`
        """
        model = ItemPickListEntryDtoEnvelope()
        if include_optional:
            return ItemPickListEntryDtoEnvelope(
                is_success = True,
                error_message = '',
                correlation_id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                activity_id = '',
                result = openapi_client.models.item_pick_list_entry_dto.ItemPickListEntryDto(
                    id = '', 
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    quantity = 1.337, 
                    item_id = '', 
                    warehouse_id = '', 
                    item_pick_list_id = '', 
                    order_item_record_id = '', 
                    tenant_id = '', )
            )
        else:
            return ItemPickListEntryDtoEnvelope(
        )
        """

    def testItemPickListEntryDtoEnvelope(self):
        """Test ItemPickListEntryDtoEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
