# coding: utf-8

"""
    HrmsService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.2.5401
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.leave_type_create_dto import LeaveTypeCreateDto

class TestLeaveTypeCreateDto(unittest.TestCase):
    """LeaveTypeCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeaveTypeCreateDto:
        """Test LeaveTypeCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeaveTypeCreateDto`
        """
        model = LeaveTypeCreateDto()
        if include_optional:
            return LeaveTypeCreateDto(
                id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                description = ''
            )
        else:
            return LeaveTypeCreateDto(
                title = '',
        )
        """

    def testLeaveTypeCreateDto(self):
        """Test LeaveTypeCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
