# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.web_page_tags_api import WebPageTagsApi


class TestWebPageTagsApi(unittest.TestCase):
    """WebPageTagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebPageTagsApi()

    def tearDown(self) -> None:
        pass

    def test_create_web_page_tag_async(self) -> None:
        """Test case for create_web_page_tag_async

        Create a web page tag
        """
        pass

    def test_delete_web_page_tag_async(self) -> None:
        """Test case for delete_web_page_tag_async

        Delete a web page tag
        """
        pass

    def test_get_web_page_tag_by_id_async(self) -> None:
        """Test case for get_web_page_tag_by_id_async

        Get web page tag by ID
        """
        pass

    def test_get_web_page_tags_async(self) -> None:
        """Test case for get_web_page_tags_async

        Get web page tags
        """
        pass

    def test_update_web_page_tag_async(self) -> None:
        """Test case for update_web_page_tag_async

        Update a web page tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
