# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.blog_post_tags_api import BlogPostTagsApi


class TestBlogPostTagsApi(unittest.TestCase):
    """BlogPostTagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlogPostTagsApi()

    def tearDown(self) -> None:
        pass

    def test_create_blog_post_tag_async(self) -> None:
        """Test case for create_blog_post_tag_async

        Create a blog post tag
        """
        pass

    def test_delete_blog_post_tag_async(self) -> None:
        """Test case for delete_blog_post_tag_async

        Delete a blog post tag
        """
        pass

    def test_get_blog_post_tag_by_id_async(self) -> None:
        """Test case for get_blog_post_tag_by_id_async

        Get blog post tag by ID
        """
        pass

    def test_get_blog_post_tags_async(self) -> None:
        """Test case for get_blog_post_tags_async

        Get blog post tags
        """
        pass

    def test_update_blog_post_tag_async(self) -> None:
        """Test case for update_blog_post_tag_async

        Update a blog post tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
