# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.apple_icons import AppleIcons

class TestAppleIcons(unittest.TestCase):
    """AppleIcons unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppleIcons:
        """Test AppleIcons
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppleIcons`
        """
        model = AppleIcons()
        if include_optional:
            return AppleIcons(
                the57 = '',
                the60 = '',
                the72 = '',
                the76 = '',
                the114 = '',
                the120 = '',
                the128 = '',
                the144 = '',
                the152 = '',
                the167 = '',
                the180 = ''
            )
        else:
            return AppleIcons(
        )
        """

    def testAppleIcons(self):
        """Test AppleIcons"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
