# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.2.5401
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.x500_distinguished_name import X500DistinguishedName

class TestX500DistinguishedName(unittest.TestCase):
    """X500DistinguishedName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> X500DistinguishedName:
        """Test X500DistinguishedName
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `X500DistinguishedName`
        """
        model = X500DistinguishedName()
        if include_optional:
            return X500DistinguishedName(
                oid = openapi_client.models.oid.Oid(
                    value = '', 
                    friendly_name = '', ),
                raw_data = 'YQ==',
                name = ''
            )
        else:
            return X500DistinguishedName(
        )
        """

    def testX500DistinguishedName(self):
        """Test X500DistinguishedName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
