# coding: utf-8

"""
    ShipmentsService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.shipping_method_dto_list_envelope import ShippingMethodDtoListEnvelope

class TestShippingMethodDtoListEnvelope(unittest.TestCase):
    """ShippingMethodDtoListEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShippingMethodDtoListEnvelope:
        """Test ShippingMethodDtoListEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShippingMethodDtoListEnvelope`
        """
        model = ShippingMethodDtoListEnvelope()
        if include_optional:
            return ShippingMethodDtoListEnvelope(
                is_success = True,
                error_message = '',
                correlation_id = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                activity_id = '',
                result = [
                    openapi_client.models.shipping_method_dto.ShippingMethodDto(
                        id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        description = '', 
                        cost = 1.337, 
                        taxable = True, 
                        tax_included = True, 
                        currency_id = '', 
                        business_id = '', 
                        shipping_class_calculation_type = 'PerClass', )
                    ]
            )
        else:
            return ShippingMethodDtoListEnvelope(
        )
        """

    def testShippingMethodDtoListEnvelope(self):
        """Test ShippingMethodDtoListEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
