# coding: utf-8

"""
    HolderService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.1.4089
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_update_dto import UserUpdateDto

class TestUserUpdateDto(unittest.TestCase):
    """UserUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUpdateDto:
        """Test UserUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdateDto`
        """
        model = UserUpdateDto()
        if include_optional:
            return UserUpdateDto(
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                first_name = '',
                last_name = '',
                public_name = '',
                id_provider = '',
                language_id = '',
                timezone_id = '',
                gender = '',
                city_id = '',
                currency_id = '',
                status = '',
                state_id = '',
                about = '',
                web_url = '',
                job_title = '',
                cover_url = '',
                avatar_url = '',
                git_hub_url = '',
                website_url = '',
                twitter_url = '',
                facebook_url = '',
                you_tube_url = '',
                linked_in_url = '',
                instagram_url = '',
                country_id = '',
                github_username = '',
                availability = 0
            )
        else:
            return UserUpdateDto(
        )
        """

    def testUserUpdateDto(self):
        """Test UserUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
