# coding: utf-8

"""
    InvoicingService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.invoice_update_dto import InvoiceUpdateDto

class TestInvoiceUpdateDto(unittest.TestCase):
    """InvoiceUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceUpdateDto:
        """Test InvoiceUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceUpdateDto`
        """
        model = InvoiceUpdateDto()
        if include_optional:
            return InvoiceUpdateDto(
                closed = True,
                title = '',
                user_id = '',
                tenant_id = '',
                price_list_id = '',
                description = '',
                enrollment_id = '',
                individual_id = '',
                payment_term_id = '',
                organization_id = '',
                receiver_tenant_id = '',
                first_name = '',
                last_name = '',
                company_name = '',
                billing_email = '',
                address_line1 = '',
                address_line2 = '',
                postal_code = '',
                country_id = '',
                state_id = '',
                city_id = '',
                billing_location_id = '',
                shipping_location_id = '',
                shipping_method_id = '',
                forex_rate = 1.337,
                currency_id = '',
                total_detail = 1.337,
                total_detail_currency_id = '',
                total_profit = 1.337,
                total_profit_currency_id = '',
                total_discounts = 1.337,
                total_discounts_currency_id = '',
                total_surcharges = 1.337,
                total_surcharges_currency_id = '',
                total_shipping_tax = 1.337,
                total_shipping_tax_currency_id = '',
                total_shipping_cost = 1.337,
                total_shipping_cost_currency_id = '',
                total_global_discounts = 1.337,
                total_global_discounts_currency_id = '',
                total_global_surcharges = 1.337,
                total_global_surcharges_currency_id = '',
                total_withheld_tax = 1.337,
                total_withheld_tax_currency_id = '',
                total_tax_base = 1.337,
                total_tax_base_currency_id = '',
                total_taxes = 1.337,
                total_taxes_currency_id = '',
                total = 1.337,
                total_currency_id = '',
                cost_calculation_method = 'Automatic',
                tax_calculation_method = 'Included',
                paid = True,
                number = 56,
                notes = '',
                order_id = '',
                enumeration = '',
                payment_mode_id = '',
                enumeration_range_id = '',
                emisor_billing_profile_id = '',
                receiver_billing_profile_id = '',
                emisor_wallet_account_id = '',
                receiver_wallet_account_id = '',
                customer_notes = '',
                invoice_type = 'PurchaseInvoice',
                document_type = 'Standard',
                invoice_status = 'Draft',
                payment_due = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                valid_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                valid_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                invoice_lines = [
                    openapi_client.models.invoice_line_create_dto.InvoiceLineCreateDto(
                        id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        closed = True, 
                        title = '', 
                        price_list_id = '', 
                        description = '', 
                        individual_id = '', 
                        payment_term_id = '', 
                        organization_id = '', 
                        receiver_tenant_id = '', 
                        first_name = '', 
                        last_name = '', 
                        company_name = '', 
                        billing_email = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        postal_code = '', 
                        country_id = '', 
                        state_id = '', 
                        city_id = '', 
                        forex_rate = 1.337, 
                        currency_id = '', 
                        total_detail = 1.337, 
                        total_detail_currency_id = '', 
                        total_profit = 1.337, 
                        total_profit_currency_id = '', 
                        total_discounts = 1.337, 
                        total_discounts_currency_id = '', 
                        total_surcharges = 1.337, 
                        total_surcharges_currency_id = '', 
                        total_shipping_cost = 1.337, 
                        total_shipping_cost_currency_id = '', 
                        total_shipping_tax = 1.337, 
                        total_shipping_tax_currency_id = '', 
                        total_withheld_tax = 1.337, 
                        total_withheld_tax_currency_id = '', 
                        total_tax_base = 1.337, 
                        total_tax_base_currency_id = '', 
                        total_taxes = 1.337, 
                        total_taxes_currency_id = '', 
                        total_global_surcharges = 1.337, 
                        total_global_surcharges_currency_id = '', 
                        total_global_discounts = 1.337, 
                        total_global_discounts_currency_id = '', 
                        total = 1.337, 
                        total_currency_id = '', 
                        cost_calculation_method = 'Automatic', 
                        tax_calculation_method = 'Included', 
                        quantity = 56, 
                        item_id = '', 
                        invoice_id = '', 
                        item_price_id = '', )
                    ],
                invoice_references = [
                    openapi_client.models.invoice_reference_create_dto.InvoiceReferenceCreateDto(
                        id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        referenced_invoice_id = '', )
                    ],
                invoice_adjustments = [
                    openapi_client.models.invoice_adjustment_create_dto.InvoiceAdjustmentCreateDto(
                        id = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        currency_id = '', 
                        description = '', 
                        surcharge_percent = 1.337, 
                        surcharge_amount = 1.337, 
                        discount_percent = 1.337, 
                        discount_amount = 1.337, 
                        total_surcharge = 1.337, 
                        total_discount = 1.337, 
                        type = 'Discount', )
                    ]
            )
        else:
            return InvoiceUpdateDto(
        )
        """

    def testInvoiceUpdateDto(self):
        """Test InvoiceUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
