# coding: utf-8

# flake8: noqa

"""
    SystemService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.antiforgery_api import AntiforgeryApi
from openapi_client.api.emails_api import EmailsApi
from openapi_client.api.fenix_alliance_abp_web_api import FenixAllianceABPWebApi
from openapi_client.api.licensing_api import LicensingApi
from openapi_client.api.migrations_api import MigrationsApi
from openapi_client.api.modules_api import ModulesApi
from openapi_client.api.options_api import OptionsApi
from openapi_client.api.tenants_api import TenantsApi
from openapi_client.api.users_api import UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.access_token_response import AccessTokenResponse
from openapi_client.models.boolean_envelope import BooleanEnvelope
from openapi_client.models.cart_dto import CartDto
from openapi_client.models.email_dispatch_request import EmailDispatchRequest
from openapi_client.models.empty_envelope import EmptyEnvelope
from openapi_client.models.error_envelope import ErrorEnvelope
from openapi_client.models.extended_tenant_dto import ExtendedTenantDto
from openapi_client.models.extended_tenant_dto_list_envelope import ExtendedTenantDtoListEnvelope
from openapi_client.models.extended_user_dto import ExtendedUserDto
from openapi_client.models.extended_user_dto_envelope import ExtendedUserDtoEnvelope
from openapi_client.models.extended_user_dto_list_envelope import ExtendedUserDtoListEnvelope
from openapi_client.models.forgot_password_request import ForgotPasswordRequest
from openapi_client.models.http_validation_problem_details import HttpValidationProblemDetails
from openapi_client.models.i_swagger_contact import ISwaggerContact
from openapi_client.models.i_swagger_endpoint import ISwaggerEndpoint
from openapi_client.models.i_swagger_license import ISwaggerLicense
from openapi_client.models.i_swagger_spec import ISwaggerSpec
from openapi_client.models.i_validation_failure import IValidationFailure
from openapi_client.models.i_validation_failure_list_envelope import IValidationFailureListEnvelope
from openapi_client.models.info_request import InfoRequest
from openapi_client.models.info_response import InfoResponse
from openapi_client.models.int32_envelope import Int32Envelope
from openapi_client.models.license_validation_request import LicenseValidationRequest
from openapi_client.models.login_request import LoginRequest
from openapi_client.models.module import Module
from openapi_client.models.module_list_envelope import ModuleListEnvelope
from openapi_client.models.object_email_dispatch_request import ObjectEmailDispatchRequest
from openapi_client.models.option_create_dto import OptionCreateDto
from openapi_client.models.option_dto import OptionDto
from openapi_client.models.option_dto_envelope import OptionDtoEnvelope
from openapi_client.models.option_dto_list_envelope import OptionDtoListEnvelope
from openapi_client.models.option_update_dto import OptionUpdateDto
from openapi_client.models.refresh_request import RefreshRequest
from openapi_client.models.register_request import RegisterRequest
from openapi_client.models.resend_confirmation_email_request import ResendConfirmationEmailRequest
from openapi_client.models.reset_password_request import ResetPasswordRequest
from openapi_client.models.social_profile_dto import SocialProfileDto
from openapi_client.models.string_list_envelope import StringListEnvelope
from openapi_client.models.studio_module import StudioModule
from openapi_client.models.studio_module_list_envelope import StudioModuleListEnvelope
from openapi_client.models.suite_license_assignment_dto import SuiteLicenseAssignmentDto
from openapi_client.models.suite_license_assignment_dto_list_envelope import SuiteLicenseAssignmentDtoListEnvelope
from openapi_client.models.suite_license_dto import SuiteLicenseDto
from openapi_client.models.suite_license_dto_envelope import SuiteLicenseDtoEnvelope
from openapi_client.models.suite_license_dto_list_envelope import SuiteLicenseDtoListEnvelope
from openapi_client.models.tenant_create_dto import TenantCreateDto
from openapi_client.models.tenant_dto import TenantDto
from openapi_client.models.tenant_dto_envelope import TenantDtoEnvelope
from openapi_client.models.tenant_dto_list_envelope import TenantDtoListEnvelope
from openapi_client.models.tenant_update_dto import TenantUpdateDto
from openapi_client.models.two_factor_request import TwoFactorRequest
from openapi_client.models.two_factor_response import TwoFactorResponse
from openapi_client.models.user_create_dto import UserCreateDto
from openapi_client.models.user_dto import UserDto
from openapi_client.models.user_dto_envelope import UserDtoEnvelope
from openapi_client.models.user_dto_list_envelope import UserDtoListEnvelope
from openapi_client.models.user_settings_dto import UserSettingsDto
from openapi_client.models.user_update_dto import UserUpdateDto
from openapi_client.models.wallet_dto import WalletDto
