# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Background(BaseModel):
    """
    Background
    """ # noqa: E501
    bg_repeat: Optional[StrictStr] = Field(default=None, alias="bgRepeat")
    bg_position: Optional[StrictStr] = Field(default=None, alias="bgPosition")
    background_color: Optional[StrictStr] = Field(default=None, alias="backgroundColor")
    background_image_url: Optional[StrictStr] = Field(default=None, alias="backgroundImageUrl")
    enable_full_width_background_image: Optional[StrictBool] = Field(default=None, alias="enableFullWidthBackgroundImage")
    __properties: ClassVar[List[str]] = ["bgRepeat", "bgPosition", "backgroundColor", "backgroundImageUrl", "enableFullWidthBackgroundImage"]

    @field_validator('bg_repeat')
    def bg_repeat_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['All', 'Horizontally', 'Vertically', 'NoRepeat']):
            raise ValueError("must be one of enum values ('All', 'Horizontally', 'Vertically', 'NoRepeat')")
        return value

    @field_validator('bg_position')
    def bg_position_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['TopLeft', 'TopRight', 'TopCenter', 'CenterLeft', 'CenterRight', 'CenterCenter', 'BottomLeft', 'BottomRight', 'BottomCenter']):
            raise ValueError("must be one of enum values ('TopLeft', 'TopRight', 'TopCenter', 'CenterLeft', 'CenterRight', 'CenterCenter', 'BottomLeft', 'BottomRight', 'BottomCenter')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Background from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if background_color (nullable) is None
        # and model_fields_set contains the field
        if self.background_color is None and "background_color" in self.model_fields_set:
            _dict['backgroundColor'] = None

        # set to None if background_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.background_image_url is None and "background_image_url" in self.model_fields_set:
            _dict['backgroundImageUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Background from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bgRepeat": obj.get("bgRepeat"),
            "bgPosition": obj.get("bgPosition"),
            "backgroundColor": obj.get("backgroundColor"),
            "backgroundImageUrl": obj.get("backgroundImageUrl"),
            "enableFullWidthBackgroundImage": obj.get("enableFullWidthBackgroundImage")
        })
        return _obj


