# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MeasurementOptions(BaseModel):
    """
    MeasurementOptions
    """ # noqa: E501
    default_weight_unit: Optional[StrictStr] = Field(default=None, alias="defaultWeightUnit")
    default_dimension_u_init: Optional[StrictStr] = Field(default=None, alias="defaultDimensionUInit")
    __properties: ClassVar[List[str]] = ["defaultWeightUnit", "defaultDimensionUInit"]

    @field_validator('default_weight_unit')
    def default_weight_unit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Kg', 'g', 'lbs', 'oz']):
            raise ValueError("must be one of enum values ('Kg', 'g', 'lbs', 'oz')")
        return value

    @field_validator('default_dimension_u_init')
    def default_dimension_u_init_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['cms', 'm', 'mm', 'inc', 'yr']):
            raise ValueError("must be one of enum values ('cms', 'm', 'mm', 'inc', 'yr')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeasurementOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeasurementOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultWeightUnit": obj.get("defaultWeightUnit"),
            "defaultDimensionUInit": obj.get("defaultDimensionUInit")
        })
        return _obj


