# coding: utf-8

"""
    ContentService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.2.5532
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MenuContextItemDto(BaseModel):
    """
    MenuContextItemDto
    """ # noqa: E501
    id: Optional[StrictStr] = None
    timestamp: Optional[datetime] = None
    order: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    text: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    icon: Optional[StrictStr] = None
    target: Optional[StrictStr] = None
    tooltip: Optional[StrictStr] = None
    parent_menu_context_item_id: Optional[StrictStr] = Field(default=None, alias="parentMenuContextItemId")
    menu_context_id: Optional[StrictStr] = Field(default=None, alias="menuContextId")
    __properties: ClassVar[List[str]] = ["id", "timestamp", "order", "name", "text", "url", "icon", "target", "tooltip", "parentMenuContextItemId", "menuContextId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MenuContextItemDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if icon (nullable) is None
        # and model_fields_set contains the field
        if self.icon is None and "icon" in self.model_fields_set:
            _dict['icon'] = None

        # set to None if target (nullable) is None
        # and model_fields_set contains the field
        if self.target is None and "target" in self.model_fields_set:
            _dict['target'] = None

        # set to None if tooltip (nullable) is None
        # and model_fields_set contains the field
        if self.tooltip is None and "tooltip" in self.model_fields_set:
            _dict['tooltip'] = None

        # set to None if parent_menu_context_item_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_menu_context_item_id is None and "parent_menu_context_item_id" in self.model_fields_set:
            _dict['parentMenuContextItemId'] = None

        # set to None if menu_context_id (nullable) is None
        # and model_fields_set contains the field
        if self.menu_context_id is None and "menu_context_id" in self.model_fields_set:
            _dict['menuContextId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MenuContextItemDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "timestamp": obj.get("timestamp"),
            "order": obj.get("order"),
            "name": obj.get("name"),
            "text": obj.get("text"),
            "url": obj.get("url"),
            "icon": obj.get("icon"),
            "target": obj.get("target"),
            "tooltip": obj.get("tooltip"),
            "parentMenuContextItemId": obj.get("parentMenuContextItemId"),
            "menuContextId": obj.get("menuContextId")
        })
        return _obj


