# coding: utf-8

"""
    SupportService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0.0
    Contact: support@fenix-alliance.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.helpdesk_api import HelpdeskApi


class TestHelpdeskApi(unittest.TestCase):
    """HelpdeskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HelpdeskApi()

    def tearDown(self) -> None:
        pass

    def test_create_inquiry_request_async(self) -> None:
        """Test case for create_inquiry_request_async

        Create an inquiry request
        """
        pass

    def test_create_knowledge_article_async(self) -> None:
        """Test case for create_knowledge_article_async

        Create a knowledge article
        """
        pass

    def test_create_maintenance_visit_async(self) -> None:
        """Test case for create_maintenance_visit_async

        Create a maintenance visit
        """
        pass

    def test_create_refund_request_async(self) -> None:
        """Test case for create_refund_request_async

        Create a refund request
        """
        pass

    def test_create_return_request_async(self) -> None:
        """Test case for create_return_request_async

        Create a return request
        """
        pass

    def test_create_warranty_request_async(self) -> None:
        """Test case for create_warranty_request_async

        Create a warranty request
        """
        pass

    def test_delete_inquiry_request_async(self) -> None:
        """Test case for delete_inquiry_request_async

        Delete an inquiry request
        """
        pass

    def test_delete_knowledge_article_async(self) -> None:
        """Test case for delete_knowledge_article_async

        Delete a knowledge article
        """
        pass

    def test_delete_maintenance_visit_async(self) -> None:
        """Test case for delete_maintenance_visit_async

        Delete a maintenance visit
        """
        pass

    def test_delete_refund_request_async(self) -> None:
        """Test case for delete_refund_request_async

        Delete a refund request
        """
        pass

    def test_delete_return_request_async(self) -> None:
        """Test case for delete_return_request_async

        Delete a return request
        """
        pass

    def test_delete_warranty_request_async(self) -> None:
        """Test case for delete_warranty_request_async

        Delete a warranty request
        """
        pass

    def test_get_inquiry_request_async(self) -> None:
        """Test case for get_inquiry_request_async

        Retrieve an inquiry request by ID
        """
        pass

    def test_get_inquiry_requests_async(self) -> None:
        """Test case for get_inquiry_requests_async

        Retrieve inquiry requests
        """
        pass

    def test_get_inquiry_requests_count_async(self) -> None:
        """Test case for get_inquiry_requests_count_async

        Get inquiry requests count
        """
        pass

    def test_get_knowledge_article_async(self) -> None:
        """Test case for get_knowledge_article_async

        Retrieve a knowledge article by ID
        """
        pass

    def test_get_knowledge_articles_async(self) -> None:
        """Test case for get_knowledge_articles_async

        Retrieve knowledge articles
        """
        pass

    def test_get_knowledge_articles_count_async(self) -> None:
        """Test case for get_knowledge_articles_count_async

        Get knowledge articles count
        """
        pass

    def test_get_maintenance_visit_async(self) -> None:
        """Test case for get_maintenance_visit_async

        Retrieve a maintenance visit by ID
        """
        pass

    def test_get_maintenance_visits_async(self) -> None:
        """Test case for get_maintenance_visits_async

        Retrieve maintenance visits
        """
        pass

    def test_get_maintenance_visits_count_async(self) -> None:
        """Test case for get_maintenance_visits_count_async

        Get maintenance visits count
        """
        pass

    def test_get_refund_request_async(self) -> None:
        """Test case for get_refund_request_async

        Retrieve a refund request by ID
        """
        pass

    def test_get_refund_requests_async(self) -> None:
        """Test case for get_refund_requests_async

        Retrieve refund requests
        """
        pass

    def test_get_refund_requests_count_async(self) -> None:
        """Test case for get_refund_requests_count_async

        Get refund requests count
        """
        pass

    def test_get_return_request_async(self) -> None:
        """Test case for get_return_request_async

        Retrieve a return request by ID
        """
        pass

    def test_get_return_requests_async(self) -> None:
        """Test case for get_return_requests_async

        Retrieve return requests
        """
        pass

    def test_get_return_requests_count_async(self) -> None:
        """Test case for get_return_requests_count_async

        Get return requests count
        """
        pass

    def test_get_warranty_request_async(self) -> None:
        """Test case for get_warranty_request_async

        Retrieve a warranty request by ID
        """
        pass

    def test_get_warranty_requests_async(self) -> None:
        """Test case for get_warranty_requests_async

        Retrieve warranty requests
        """
        pass

    def test_get_warranty_requests_count_async(self) -> None:
        """Test case for get_warranty_requests_count_async

        Get warranty requests count
        """
        pass

    def test_update_inquiry_request_async(self) -> None:
        """Test case for update_inquiry_request_async

        Update an inquiry request
        """
        pass

    def test_update_knowledge_article_async(self) -> None:
        """Test case for update_knowledge_article_async

        Update a knowledge article
        """
        pass

    def test_update_maintenance_visit_async(self) -> None:
        """Test case for update_maintenance_visit_async

        Update a maintenance visit
        """
        pass

    def test_update_refund_request_async(self) -> None:
        """Test case for update_refund_request_async

        Update a refund request
        """
        pass

    def test_update_return_request_async(self) -> None:
        """Test case for update_return_request_async

        Update a return request
        """
        pass

    def test_update_warranty_request_async(self) -> None:
        """Test case for update_warranty_request_async

        Update a warranty request
        """
        pass


if __name__ == '__main__':
    unittest.main()
